/*
  In a collaborative editing system, instead of sending the entire document
  whenever a change occurs, the application sends small "operations".
  These operations describe what change happened.

  Example:
  If a user makes some text bold, the system sends an operation that includes:
  - the type of action (format)
  - the tag to apply (for example bold/strong)
  - the range of text where the formatting happened

  Other connected clients receive this operation from the server.

  When an operation arrives, the editor needs to reproduce the same change
  locally so that all users see the same document.

  The logic listens for incoming operations through a real-time communication
  channel such as WebSockets.

  When an operation is received:
  1. The editor first checks if the operation was generated by the same user.
     If it was, the operation is ignored to prevent applying the same
     formatting twice.

  2. If the operation is valid and represents a formatting action,
     the editor reconstructs the exact text range using the start
     and end offsets provided in the operation.

  3. After reconstructing the range, the editor creates the appropriate
     formatting element (such as bold or italic).

  4. The selected text is then wrapped with that formatting element.

  This reproduces the formatting change that another user performed.

  By broadcasting operations and replaying them on every client,
  all connected users stay synchronized and see the same document state.
*/
