/*
==================================================
CSRF TOKENS (Frontend System Design)
==================================================

Definition:
- CSRF (Cross-Site Request Forgery) token is a unique, secret value
- Generated by the backend and sent to the frontend
- Used to verify that a request is coming from the legitimate user/app


--------------------------------------------------
🚨 PROBLEM: WHAT IS CSRF?
--------------------------------------------------

 Scenario:
 1. User logs into bank.com
 2. Auth cookie is stored in browser (HttpOnly)
 3. User visits malicious-site.com
 4. Malicious site sends request to bank.com:

POST /transfer-money
amount=1000

 Browser automatically attaches cookies 😬
 Backend thinks it's a valid user request

 → This is a CSRF attack


--------------------------------------------------
🛡️ SOLUTION: CSRF TOKEN
--------------------------------------------------

 Backend generates a CSRF token:
 Example: "XyZ123abc"

 Sends it to frontend (NOT HttpOnly cookie or API response)

 Frontend must include it in every sensitive request:

fetch('/transfer', {
  method: 'POST',
  headers: {
    'X-CSRF-Token': 'XyZ123abc'
  }
})


 Backend verifies:
 - Does request contain correct CSRF token?
 - If yes → allow
 - If no → reject


--------------------------------------------------
🔑 WHY IT WORKS
--------------------------------------------------

 Malicious site cannot read your CSRF token
 (same-origin policy blocks access)

 So attacker:
 ✔ Can send request
 ❌ Cannot attach correct CSRF token

 → Request gets rejected


--------------------------------------------------
🧠 IMPORTANT POINTS
--------------------------------------------------

 - CSRF tokens are needed when using cookies for auth
 - Not needed if using Authorization headers (JWT in memory)
 - Must be:
   → Unique per session (or per request)
   → Hard to guess


--------------------------------------------------
🛠️ COMMON IMPLEMENTATION
--------------------------------------------------

 1. Backend sends CSRF token in:
    → API response OR
    → non-HttpOnly cookie

 2. Frontend stores it (memory)

 3. Frontend attaches it in headers for sensitive requests


--------------------------------------------------
🎯 FINAL SUMMARY
--------------------------------------------------

 CSRF token = proof that request came from your frontend
 Protects against malicious cross-site requests
 Required when using cookie-based authentication

*/
